### ISSUE TITLE
Change input source

### ISSUE THREAD

**Issue by abuzaina** [kuronekodaisuki/StitchCam#2]
How could the input source to be changed from usb cameras to saved videos or any other source ?

**Comment by kuronekodaisuki** [comment]
Show me your camera interface, please.

**Comment by abuzaina** [comment]
I am using the FlyCapture2 api to access the PointGrey cameras, here is a sample code to convert the grabbed frames to OpenCV
https://gist.github.com/kevinhughes27/5543668
and here are more OpenCV samples from PointGrey
https://www.ptgrey.com/Content/Images/Uploaded/KB-Data/OpenCV-samples.zip

**Comment by kuronekodaisuki** [comment]
Show me platform information - Windows ? or Ubuntu?
I have PointGrey's Firewire cameras and tried it.

**Comment by kuronekodaisuki** [comment]
Try this sample program.

#include "FlyCapture2.h"

#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <iostream>

#include "MyStitcher.h"
#include "MyBlender.h"
#include "MyCompensator.h"
#include "MySeamFinder.h"
#include "MyWarper.h"

using namespace FlyCapture2;
using namespace cv;

// Capture and convert to mat
Mat capture(Camera & camera)
{
		// Get the image
	Image rawImage;
	Error error = camera.RetrieveBuffer( &rawImage );
	if ( error != PGRERROR_OK )
	{
			std::cout << "capture error" << std::endl;
			continue;
	}

	// convert to rgb
	Image rgbImage;
	rawImage.Convert( FlyCapture2::PIXEL_FORMAT_BGR, &rgbImage );

	// convert to OpenCV Mat
	unsigned int rowBytes = (double)rgbImage.GetReceivedDataSize()/(double)rgbImage.GetRows();	   
	Mat image = cv::Mat(rgbImage.GetRows(), rgbImage.GetCols(), CV_8UC3, rgbImage.GetData(),rowBytes);
	return image;
}

int main()
{
	Error error;
	Camera camera0, camera1;
	CameraInfo camInfo;

	int count = gpu::getCudaEnabledDeviceCount();
	printf("CUDA device count:%d\n", count);
	for (int i = 0; i < count; i++)
	{
		gpu::DeviceInfo info(i);
		cout << info.name() << endl;
	}

	MyStitcher stitcher = MyStitcher::createDefault(true);
	stitcher.setSeamFinder(new detail::MyVoronoiSeamFinder());
	stitcher.setBlender(new detail::MyBlender(true));
	stitcher.setExposureCompensator(new detail::MyCompensator(true));
	
	// Connect the camera
	error = camera0.Connect(0);
	error = camera1.Connect(1);

	error = camera0.StartCapture();
	error = camera1.StartCapture();

	bool res, continuous = false;
	vector<Mat> images;
	Mat left, right;

	// Capture loop
	for (bool loop = true; loop; )
	{
		Mat image, panorama;

		left = capture(camera0);
		right = capture(camera1);
		images.push_back(left);
		images.push_back(right);
		imshow("camera0", left);
		imshow("camera1", right);
		
		char key = (char)waitKey(10);
		switch (key)
		{
		case 'q':
		case 'Q':
			loop = false;
			break;

		case 's':
		case 'S':
			continuous = !continuous;
			break;

		case 'c':
		case 'C':
			start = getTick();
			switch (stitcher.stitch(images, panorama))
			{
			case MyStitcher::OK:
				printf("%d msec\n", getTick() - start);
				imshow("Panorama", panorama);
				break;

			case MyStitcher::ERR_NEED_MORE_IMGS:
				printf("Need more IMAGES\n");
				break;

			default:
				printf("Failed to stitch\n");
			}
			break;
		case 'n': // NoSeamFinder
			stitcher.setSeamFinder(new detail::NoSeamFinder());
			printf("NoSeamFinder\n");
			break;
		case 'v': // VoronoiSeamFinder
			stitcher.setSeamFinder(new detail::MyVoronoiSeamFinder());
			printf("VoronoiSeamFinder\n");
			break;
		case 'd': // DpSeamFinder
			stitcher.setSeamFinder(new detail::MySeamFinder());
			printf("DpSeamFinder\n");
			break;
		}
		
		// Do stitch
		if (continuous) {
			start = getTick();
			if (MyStitcher::OK == stitcher.composePanorama(images, panorama)) {
				printf("%d msec\n", getTick() - start);
				imshow("Panorama", panorama);
			}
		}
		images.clear();
	}
	
	camera0.StopCapture();
	camera1.StopCapture();

	camera0.Disconnect();
	camera1.Disconnect();

	return 0;
}

**Comment by abuzaina** [comment]
Great, thank you very much. I am on Ubuntu L4T. I will try it and let you know.
